#!/bin/sh

#Skripta za generiranje certifikata za eduroam mrežu. Varijable ispod je potrebno zamijeniti s odgovarajućima.
putanja="/home/linux korisničko ime/.cache/ca.foi.hr.der" # ovdje mora biti apsolutna putanja
user='linux korisničko ime'

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
echo "Unesite e-mail"
read email
echo "Unesite lozinku"
read -s lozinka
[ -z $1 ] || putanja=$(realpath "$1")

echo "ctrl_interface=/var/run/wpa_supplicant

network={
      ssid=\"eduroam\"
      proto=WPA2 WPA
      key_mgmt=WPA-EAP
      pairwise=CCMP TKIP
      group=CCMP TKIP
      ca_cert=\""$putanja"\"
      subject_match=\"freeradius.foi.hr\"
      identity=\""$email"\"
      eap=TTLS
      password=\""$lozinka"\"
      phase2=\"auth=PAP\"

     }
" > /etc/wpa_supplicant/eduroam ;

echo "ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=root
ap_scan=0
network={
        key_mgmt=IEEE8021X
        eap=TTLS
        anonymous_identity=\"anonymous@foi.hr\"
        identity=\""$email"\"
        password=\""$lozinka"\"
        ca_cert=\""$putanja"\"
        phase2=\"auth=PAP\"
}
" > /etc/wpa_supplicant/eduroamw ;

# Bonus dio - enkripcija .conf datoteke, kako lozinka ne bi bila u plain textu.
# Ako nemate, potrebno je generirati GPG ključ pomoću gpg --full-generate-key
# Otkomentirati naredbe ispod za korištenje, skripta eduroam se sama otkomentira.

# PGPmail='e-mail od GPG certifikata'
# mv /etc/wpa_supplicant/eduroam /etc/wpa_supplicant/eduroamw /tmp/
# su - $user -c "gpg --no-tty --encrypt -r $PGPmail /tmp/eduroam"
# su - $user -c "gpg --no-tty --encrypt -r $PGPmail /tmp/eduroamw"
# rm /tmp/eduroam /tmp/eduroamw &>/dev/null
# mv /tmp/eduroam.gpg /tmp/eduroamw.gpg /etc/wpa_supplicant
# sed -i '13,15s/^# //' eduroam
# sed -i '35s/^# //' eduroam
